# Use root/example as user/password credentials
version: '3.1'

services:
  db-postgres:
    image: postgres:latest
    container_name: tfm-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test

  mongo:
    image: mongo
    container_name: tfm-mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
